/*
  Auto-generated by Spline
*/
import React, {
  Suspense,
  useRef,
  useEffect,
  forwardRef,
  useState,
} from 'react';
import { useNavigate } from 'react-router-dom';
import styled from 'styled-components';
import Spline from '@splinetool/react-spline';
// const Spline = React.lazy(() => import('@splinetool/react-spline'));

export default function SplineObject({ ...props }) {
  const [spline, setSpline] = useState();

  function onLoad(spline) {
    setSpline(spline);
  }

  const handleZoomIn = () => {
    spline.setZoom(100);
    console.log('zoomin in');
  };

  const handleZoomOut = () => {
    spline.setZoom(1); // Zoom out by 20%
    console.log('zoomin out');
  };

  return (
    <div>
      <button type='button' onClick={handleZoomIn}>
        Zoom in
      </button>
      <button type='button' onClick={handleZoomOut}>
        Zoom out
      </button>
      <Spline
        onLoad={onLoad}
        scene='https://prod.spline.design/EaVEPovGuLXxV1Bk/scene.splinecode'
      />
    </div>
  );
}
