/*
  Auto-generated by Spline
*/
import React, { Suspense } from 'react';
import useSpline from '@splinetool/r3f-spline';
import { OrthographicCamera } from '@react-three/drei';

export default function SplineObject({ ...props }) {
  const { nodes, materials } = useSpline(
    'https://prod.spline.design/EaVEPovGuLXxV1Bk/scene.splinecode'
  );
  return (
    <>
      {/* <color attach='background' args={['#d5dcf2']} /> */}
      <Suspense fallback={<h1>Loading...</h1>}>
        <group {...props} dispose={null}>
          <group name='Phobigone' position={[0, -110, 0]}>
            <group name='Browser' position={[-32.52, 33.55, 197.44]}>
              <group
                name='bridge'
                position={[1.23, -130.98, -229.13]}
                rotation={[0, -Math.PI / 2, 0]}
                scale={[0.16, 2.43, 1.97]}
              >
                <group name='star' position={[163.27, 87.79, -19.94]}>
                  <mesh
                    name='star1'
                    geometry={nodes.star1.geometry}
                    material={nodes.star1.material}
                    castShadow
                    receiveShadow
                    position={[0, -9.19, 20]}
                    rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                    scale={0}
                  />
                </group>
                <mesh
                  name='bridge_one_pole'
                  geometry={nodes.bridge_one_pole.geometry}
                  material={nodes.bridge_one_pole.material}
                  castShadow
                  receiveShadow
                  position={[47.32, 0, 0]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                />
              </group>
              <group name='Browser Instance' position={[-8.79, 76.68, -216.08]}>
                <group name='Content' position={[0, -20.62, 19.96]}>
                  <mesh
                    name='Content1'
                    geometry={nodes.Content1.geometry}
                    material={materials['Untitled Material']}
                    castShadow
                    receiveShadow
                    position={[0, 0, -4.5]}
                  />
                </group>
                <mesh
                  name='Window Main'
                  geometry={nodes['Window Main'].geometry}
                  material={materials['Untitled Material']}
                  castShadow
                  receiveShadow
                  position={[0, 32.51, -0.85]}
                  scale={[1, 1, 0.23]}
                />
                <mesh
                  name='Window Top'
                  geometry={nodes['Window Top'].geometry}
                  material={materials['Untitled Material']}
                  castShadow
                  receiveShadow
                  position={[0, 34.48, -0.85]}
                  scale={[1, 1, 0.23]}
                />
                <group
                  name='Browser Buttons'
                  position={[-220.07, 186.62, 10.93]}
                >
                  <group name='Clone 0'>
                    <mesh
                      name='browser_button'
                      geometry={nodes.browser_button.geometry}
                      material={materials['Untitled Material']}
                      castShadow
                      receiveShadow
                    />
                  </group>
                  <group name='Clone 1' position={[35.5, 0, 0]}>
                    <mesh
                      name='browser_button1'
                      geometry={nodes.browser_button1.geometry}
                      material={materials['Untitled Material']}
                      castShadow
                      receiveShadow
                    />
                  </group>
                  <group name='Clone 2' position={[71, 0, 0]}>
                    <mesh
                      name='browser_button2'
                      geometry={nodes.browser_button2.geometry}
                      material={materials['Untitled Material']}
                      castShadow
                      receiveShadow
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
          <group name='Deleted Components' visible={false}>
            <group name='Browser1' position={[0, 0, 0]}>
              <group name='Content2' position={[0, -20.62, 19.96]}>
                <mesh
                  name='Content3'
                  geometry={nodes.Content3.geometry}
                  material={materials['Content3 Material']}
                  castShadow
                  receiveShadow
                  position={[0, 0, -4.5]}
                />
              </group>
              <mesh
                name='Window Main1'
                geometry={nodes['Window Main1'].geometry}
                material={materials['Window Main1 Material']}
                castShadow
                receiveShadow
                position={[0, 32.51, -0.85]}
                scale={[1, 1, 0.23]}
              />
              <mesh
                name='Window Top1'
                geometry={nodes['Window Top1'].geometry}
                material={materials['Window Top1 Material']}
                castShadow
                receiveShadow
                position={[0, 34.48, -0.85]}
                scale={[1, 1, 0.23]}
              />
              <group
                name='Browser Buttons1'
                position={[-220.07, 186.62, 10.93]}
              >
                <group name='Clone 01'>
                  <mesh
                    name='browser_button3'
                    geometry={nodes.browser_button3.geometry}
                    material={materials['Untitled Material']}
                    castShadow
                    receiveShadow
                  />
                </group>
                <group name='Clone 11' position={[35.5, 0, 0]}>
                  <mesh
                    name='browser_button4'
                    geometry={nodes.browser_button4.geometry}
                    material={materials['Untitled Material']}
                    castShadow
                    receiveShadow
                  />
                </group>
                <group name='Clone 21' position={[71, 0, 0]}>
                  <mesh
                    name='browser_button5'
                    geometry={nodes.browser_button5.geometry}
                    material={materials['Untitled Material']}
                    castShadow
                    receiveShadow
                  />
                </group>
              </group>
            </group>
            <group name='browser_button6' position={[-216.44, 187.07, 9.17]}>
              <mesh
                name='browser_button7'
                geometry={nodes.browser_button7.geometry}
                material={materials['browser_button7 Material']}
                castShadow
                receiveShadow
              />
            </group>
          </group>
          <directionalLight
            name='Directional Light'
            intensity={0.97}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            position={[850000, 1300000, 1001000]}
            rotation={[0, 0, 0]}
          />
          <OrthographicCamera
            name='1'
            makeDefault={true}
            zoom={0.54}
            far={100000}
            near={-100000}
            position={[1321.9, 758.43, 2779.63]}
            rotation={[-0.29, 0.46, 0.13]}
            scale={1}
          />
        </group>
      </Suspense>
    </>
  );
}
